jobeet/src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="categories")
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @var string
     * 
     * @Gedmo\Slug(fields={"name"})
     * 
     * @ORM\Column(type="string", length=150, unique=true)
     */
    private $slug;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @var Job[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Job", mappedBy="category")
     */
    private $jobs;

    /**
     * @var Affiliate[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Affiliate", mappedBy="categories")
     */
    private $affiliates;

    public function __construct()
    {
        $this->jobs = new ArrayCollection();
        $this->affiliates = new ArrayCollection();
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): void
    {
        $this->slug = $slug;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Job[]
     */
    public function getJobs(): Collection
    {
        return $this->jobs;
    }

    public function addJob(Job $job): self
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs[] = $job;
            $job->setCategory($this);
        }

        return $this;
    }

    public function removeJob(Job $job): self
    {
        if ($this->jobs->contains($job)) {
            $this->jobs->removeElement($job);
            // set the owning side to null (unless already changed)
            if ($job->getCategory() === $this) {
                $job->setCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Affiliate[]
     */
    public function getAffiliates(): Collection
    {
        return $this->affiliates;
    }

    public function addAffiliate(Affiliate $affiliate): self
    {
        if (!$this->affiliates->contains($affiliate)) {
            $this->affiliates[] = $affiliate;
            $affiliate->addCategory($this);
        }

        return $this;
    }

    public function removeAffiliate(Affiliate $affiliate): self
    {
        if ($this->affiliates->contains($affiliate)) {
            $this->affiliates->removeElement($affiliate);
            $affiliate->removeCategory($this);
        }

        return $this;
    }

    /**
     * @return Job[]|ArrayCollection
     */
    public function getActiveJobs()
    {
        return $this->jobs->filter(function (Job $job) {
            return $job->getExpiresAt() > new \DateTime;
        });
    }
}

jobeet/src/Form/JobType.php
<?php 
namespace App\Form;

use App\Entity\Category;
use App\Entity\Job;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\Image;

class JobType extends AbstractType{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormbuilderInterface $builder, array $options)
    {
        $builder
            ->add('type', ChoiceType::class,['choices' => array_combine(Job::TYPES, Job::TYPES),
            'expanded' => true,])
            ->add('company', TextType::class,['constraints' => [new NotBlank(), new Length(['max' =>25])]])
            ->add('logo', FileType::class, ['required' => false, 'constraints' => [new Image(),]])
            ->add('url', UrlType::class)
            ->add('position', TextType::class)
            ->add('location', TextType::class)
            ->add('description', TextareaType::class)
            ->add('howToApply', TextType::class)
            ->add('public', ChoiceType::class,['choices' => ['Yes' => true,'No' => false,],
            'label' => 'Public?',])
            ->add('activated', ChoiceType::class,['choices' => ['Yes' => true,'No' => false,],
            'label' => 'Activated',])
            ->add('email', EmailType::class)
            ->add('category', EntityType::class,['class' => Category::class,
            'choice_label' => 'name',]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Job::class,
        ]);
    }
}
?>

jobeet/src/Controller/Admin/JobController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use App\Service\FileUploader;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\FormInterface;
use App\Form\JobType;
use App\Entity\Job;
use Knp\Component\Pager\PaginatorInterface;


class JobController extends AbstractController
{
    /**
     * List all jobs entities
     * 
     * @Route("/admin/job/{page}", name="admin.job.list", methods="GET", defaults={"page": 1}, requirements={"page" = "\d"})
     * 
     * @param EntityManagerInterface $em
     * @param PaginatorInterface $paginator
     * @param int $page
     * 
     * @return Response
     */
    public function list(EntityManagerInterface $em, PaginatorInterface $paginator, int $page): Response
    {
        $jobs = $paginator->paginate($em->getRepository(Job::class)->findAll(), $page, 10);
        return $this->render('admin/job/list.html.twig', [
            'jobs' => $jobs,
        ]);
    }

    /**
     * @Route("/admin/job/create", name="admin.job.create", methods={"GET","POST"})
     * 
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param FileUploader fileUploader
     * 
     * @return RedirectResponse|Response
     */
    public function create(Request $request, EntityManagerInterface $em, FileUploader $fileUploader): Response
    {
        $job = new Job();
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em->persist($job); //Doctrine administra el objeto $obj
            $em->flush(); // Se lanzan las sentencias sql de los objetos administrados por document


            return $this->redirectToRoute('admin.job.list');
        }

        return $this->render('admin/job/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * Edit existing job entity
     *
     * @Route("/admin/job/{id}/edit", name="admin.job.edit", methods={"GET","POST"})
     *
     * @param Request $request
     * @param Job $job
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function edit(Request $request, Job $job, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute('admin.job.list');
        }
        return $this->render('admin/job/edit.html.twig', [
            'form' => $form->createView(),
            'job' => $job,
        ]);
    }
    
    /**
     * Delete job.
     *
     * @Route("/admin/job/{id}/delete", name="admin.job.delete", methods="DELETE",
     * requirements={"id" = "\d+"})
     *
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param Job $job
     *
     * @return Response
     */
    public function delete(Request $request, EntityManagerInterface $em, Job $job): Response
    {
        if ($this->isCsrfTokenValid('delete' . $job->getId(), $request->request->get('_token'))) {
            $em->remove($job);
            $em->flush();
        }
        return $this->redirectToRoute('admin.job.list');
    }
}

jobeet/src/Controller/JobController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Job;
use App\Repository\JobRepository;
use App\Entity\Category;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Symfony\Component\HttpFoundation\Request;
use App\Form\JobType;
use App\Service\FileUploader;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Form\FormInterface;

class JobController extends AbstractController{

/**
     * Finds and displays a job entity.
     * 
     * @Route("/job/{id}", name="job.show", methods="GET", requirements={"id" = "\d+"})
     * 
     * @Entity("job",expr="repository.findActiveJobs(id)")
     * 
     * @param Job $job
     * 
     * @return Response
     */
    public function show(Job $job) : Response
    {
        return $this->render('job/show.html.twig',[
            'job' => $job,
        ]);
    }

     /** 
     * @Route("/job/create", name="job.create", methods={"GET", "POST"})
     * 
     * @param Request $request
     * @param EntityManagerInterface $em
     * 
     * @return RedirectResponse|Response
     */
    public function create(Request $request, EntityManagerInterface $em, FileUploader $fileUploader) : Response
    {
        $job = new Job();
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $logoFile = $form->get('logo')->getData();

            if($logoFile instanceOf UploadedFile){
                $fileName=$fileUploader->upload($logoFile);
                $job->setLogo($fileName);
            }

            $em->persist($job); //Doctrine administra el objeto $obj
            $em->flush(); // Se lanzan las sentencias sql de los objetos administrados por document
        

            return $this->redirectToRoute('job.preview', [
                'token' => $job->getToken(),
            ]);
        }

        return $this->render('job/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }
     

    /**
     * Lists all job entities.
     * 
     * @Route("/job", name="job.list", methods="GET")
     * 
     * 
     * @return Response
     */

    public function list(EntityManagerInterface $em) : Response
    {
        $categories = $em->getRepository(Category::class)->findWithActiveJobs();

        return $this->render('job/list.html.twig', [
            'categories' => $categories,
        ]);
    }

     /**
    * Edit existing job entity
    *
    * @Route("/job/{token}/edit", name="job.edit", methods={"GET","POST"}, requirements={"token" = "\w+"})
    *
    * @param Request $request
    * @param Job $job
    * @param EntityManagerInterface $em
    * @return Response
    */
    public function edit(Request $request, Job $job, EntityManagerInterface $em) : Response
    {
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em->flush();
            return $this->redirectToRoute('job.list');
        }
        return $this->render('job/edit.html.twig', [
        'form' => $form->createView(),
        ]);
    }
    
     /**
     * Finds and displays the preview page for a job entity.
     *
     * @Route("job/{token}", name="job.preview", methods="GET", requirements={"token" = "\w+"})
     *
     * @param Job $job
     *
     * @return Response
     */
    public function preview(Job $job) : Response
    {
        $deleteForm = $this->createDeleteForm($job);

        return $this->render('job/show.html.twig', [
            'job' => $job,
            'hasControlAccess' => true,
            'deleteForm' => $deleteForm->createView(),
        ]);
    }

    /**
     * Creates a form to delete a job entity.
     *
     * @param Job $job
     *
     * @return FormInterface
     */
    private function createDeleteForm(Job $job) : FormInterface
    {
        return $this->createFormBuilder()
        ->setAction($this->generateUrl('job.delete', ['token' => $job->getToken()]))
        ->setMethod('DELETE')
        ->getForm();
    }


    /**
     * Delete a job entity.
     *
     * @Route("job/{token}/delete", name="job.delete", methods={"DELETE"}, requirements={"token" =
     *  "\w+"})
     * 
     * @param Request $request
     * 
     * @param Job $job
     * 
     * @param EntityManagerInterface $em
     *
     * @return Response
     */
    public function delete(Request $request, Job $job, EntityManagerInterface $em):Response
    {
        $form = $this->createDeleteForm($job);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $em->remove($job);
            $em->flush();
        }
        return $this->redirectToRoute('job.list');
    }
}


?>

jobeet/templates/job/control_panel.html.twig
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <span class="navbar-brand">Control Panel:</span>
            <a class="btn btn-default navbar-btn" href="{{ path('job.edit', {'token': job.token }) }}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
            </a>
            {{ form_start(deleteForm, {'attr': {'class': 'navbar-form navbar-left'}}) }}
                {{ form_widget(deleteForm) }}
                <button type="submit" class="btn btn-default" onclick="return confirm('Are you sure?')">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
            {{ form_end(deleteForm) }}
                {% if not(job.activated) %}
                {{ form_start(publishForm, {'attr': {'class': 'navbar-form navbar-left'}}) }}
                    {{ form_widget(publishForm) }}
                    <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Publish
                {{ form_end(publishForm) }}
            {% endif %}
        </div>
        <div class="collapse navbar-collapse">
            
            {% if job.activated %}
                {% if job.expiresAt < date() %}
                    <p class="navbar-text ">Expired</p>
                {% else %}
                    <p class="navbar-text ">Expires in <strong>{{job.expiresAt.diff(date())|date('%a') }}</strong> days</p>
                {% endif %}
                {% if job.expiresAt.diff(date())|date('%a') < 5 %}
                    <a class="btn btn-default navbar-btn" href="#">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>Extend (for another 30 days)
                    </a>
                {% endif %}
            {% else %}
            
            
                
    
            {% endif %}
            <p class="navbar-text navbar-right">
            [Bookmark this <a href="{{ url('job.preview', {token: job.token})}}">URL</a> to manage this job in the future]
            </p>
        </div>
    </div>
</nav>

jobeet/templates/job/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Job creation</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Create</button>
            </div>
        </div>
    {{ form_end(form) }}
{% endblock %}

jobeet/templates/job/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
 <h1>Job edit</h1>
 {{ form_start(form) }}
        {{ form_widget(form) }}

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Create</button>
            </div>
        </div>
    {{ form_end(form) }}
{% endblock %}

jobeet/templates/job/list.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% for category in categories %}
        <h4><a href="{{path('category.show', {slug: category.slug})}}">{{ category.name }}</a></h4>
        {% include 'job/table.html.twig' with {'jobs' : category.activeJobs | slice(0,max_jobs_on_homepage)} %}
    {% endfor %}
{% endblock %}

jobeet/templates/job/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% if hasControlAccess is defined and hasControlAccess %}
        {% include 'job/control_panel.html.twig' with {'job': job, 'deleteForm': deleteForm } %}
    {% endif %}
    <h1>Job</h1>

    <div class="media" style="margin-top: 60px;">
        {% if job.logo %}
            <div class="media-left">
                <a href="{{ job.url }}" target="_blank">
                    <img class="media-object" style="width:100px; height:100px;" src="{{ asset(jobs_web_directory ~ '/' ~ job.logo.filename) }}">
                </a>
            </div>
        {% endif %}
        <div class="media-body">
            <div class="row">
                <div class="col-sm-10">
                    <h3 class="media-heading"><strong>{{ job.company }}</strong> <i>({{ job.location }})</i></h3>
                </div>

                <div class="col-sm-2">
                    <i class="pull-right">posted on {{ job.createdat|date('d/m/Y') }}</i>
                </div>
            </div>

            <p>
                <strong>{{ job.position }}</strong>
                <small> - <i>{{ job.type }}</i></small>
            </p>

            <p>{{ job.description|nl2br }}</p>

            <p style="margin-top: 40px;">
                <strong>How to apply?</strong>
            </p>

            <p>{{ job.howToApply }}</p>

            <div class="row">
                <div class="col-sm-12 text-right">
                    <a class="btn btn-default" href="{{ path('job.list') }}">
                        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                        Back to list
                    </a>

                    {# <a class="btn btn-primary" href="#">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        Edit
                    </a> #}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

jobeet/templates/job/table.html.twig
<table class="table text-center">
    <thead>
    <tr>
        <th class="active text-center">City</th>
        <th class="active text-center">Position</th>
        <th class="active text-center">Company</th>
    </tr>
    </thead>
    <tbody>
    {% for job in jobs %}
        <tr>
            <td>{{ job.location }}</td>
            <td>
                <a href="{{ path('job.show', {id: job.id}) }}">
                    {{ job.position }}
                </a>
            </td>
            <td>{{ job.company }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>